import Link from "next/link";
import { Images, Sparkles, PackageOpen, Palette, Layers3, WandSparkles, Bot, Search, ArrowUpRight } from "lucide-react";
const features = [
  { href: "/inspiration", title: "灵感库", description: "收藏的美甲款式", icon: Images },
  { href: "/favorite-assets", title: "收藏素材", description: "收藏的单个素材或物品", icon: Sparkles },
  { href: "/assets", title: "材料库", description: "实际拥有的美甲材料", icon: PackageOpen },
  { href: "/works", title: "作品", description: "已完成的美甲作品", icon: Palette },
  { href: "/designs", title: "设计", description: "保存的设计方案与过程", icon: Layers3 },
];
export default function HomePage() {
  return <><header className="mb-10 pt-3 sm:mb-14"><p className="mb-3 text-xs font-medium uppercase tracking-[0.22em] text-accent">工作台</p><h1 className="text-3xl font-semibold tracking-[-0.04em] text-foreground sm:text-5xl">美甲设计工作台</h1><p className="mt-3 text-sm text-muted sm:text-base">离线可用 · 多设备同步</p></header><section className="grid gap-3 sm:grid-cols-2">{features.map(({ href, title, description, icon: Icon }) => <Link key={href} href={href} className="group flex min-h-32 items-start justify-between rounded-2xl border border-border bg-surface p-5 transition active:bg-surface-raised"><div><Icon size={20} strokeWidth={1.5} className="mb-5 text-muted"/><h2 className="font-medium text-foreground">{title}</h2><p className="mt-1.5 text-sm text-muted">{description}</p></div><ArrowUpRight size={16} className="text-muted" /></Link>)}</section><Link href="/create" className="mt-4 flex min-h-20 items-center justify-between rounded-2xl border border-accent bg-surface p-5 text-foreground transition active:bg-surface-raised"><div className="flex items-center gap-4"><span className="rounded-xl bg-accent p-2.5 text-background"><WandSparkles size={20}/></span><div><h2 className="font-medium">开始设计</h2><p className="mt-1 text-sm text-muted">创建新的美甲设计</p></div></div><ArrowUpRight size={18} className="text-accent" /></Link><section className="mt-12 border-t border-border pt-8"><h2 className="mb-4 text-xs font-medium uppercase tracking-[0.2em] text-muted">联网功能</h2><div className="grid gap-3 sm:grid-cols-2"><Link href="/ai" className="flex min-h-16 items-center gap-4 rounded-2xl border border-border bg-surface p-5 active:bg-surface-raised"><Bot size={20} className="text-muted"/><div><h3 className="text-sm font-medium">AI设计</h3><p className="mt-1 text-xs text-muted">即将支持</p></div></Link><Link href="/search" className="flex min-h-16 items-center gap-4 rounded-2xl border border-border bg-surface p-5 active:bg-surface-raised"><Search size={20} className="text-muted"/><div><h3 className="text-sm font-medium">联网搜索</h3><p className="mt-1 text-xs text-muted">预留入口</p></div></Link></div></section></>;
}
