import Link from "next/link";
import { Images, Sparkles, PackageOpen, Palette, Layers3, WandSparkles, Bot, Search, ArrowUpRight } from "lucide-react";
const features = [
  { href: "/inspiration", title: "灵感库", description: "收藏的美甲款式", icon: Images },
  { href: "/favorite-assets", title: "收藏素材", description: "收藏的单个素材或物品", icon: Sparkles },
  { href: "/assets", title: "素材库", description: "实际拥有的美甲素材", icon: PackageOpen },
  { href: "/works", title: "作品", description: "已完成的美甲作品", icon: Palette },
  { href: "/designs", title: "设计", description: "保存的设计方案与过程", icon: Layers3 },
];
export default function HomePage() {
  return <><header className="mb-10 pt-3 sm:mb-14"><p className="mb-3 text-xs font-medium uppercase tracking-[0.22em] text-accent">工作台</p><h1 className="text-3xl font-semibold tracking-[-0.04em] text-white sm:text-5xl">美甲设计工作台</h1><p className="mt-3 text-sm text-muted sm:text-base">离线可用 · 多设备同步</p></header><section className="grid gap-3 sm:grid-cols-2">{features.map(({ href, title, description, icon: Icon }) => <Link key={href} href={href} className="group flex min-h-32 items-start justify-between rounded-2xl border border-[#3a3a3a] bg-[#101010] p-5 transition active:border-[#666] active:bg-[#202020]"><div><Icon size={20} strokeWidth={1.5} className="mb-5 text-zinc-300"/><h2 className="font-medium text-white">{title}</h2><p className="mt-1.5 text-sm text-zinc-300">{description}</p></div><ArrowUpRight size={16} className="text-zinc-300" /></Link>)}</section><Link href="/create" className="mt-4 flex min-h-20 items-center justify-between rounded-2xl border border-purple-300/70 bg-purple-950/40 p-5 text-white transition active:bg-purple-900/50"><div className="flex items-center gap-4"><span className="rounded-xl bg-accent p-2.5 text-black"><WandSparkles size={20}/></span><div><h2 className="font-medium">开始设计</h2><p className="mt-1 text-sm text-zinc-200">创建新的美甲设计</p></div></div><ArrowUpRight size={18} className="text-purple-200" /></Link><section className="mt-12 border-t border-border pt-8"><h2 className="mb-4 text-xs font-medium uppercase tracking-[0.2em] text-zinc-400">联网功能</h2><div className="grid gap-3 sm:grid-cols-2"><Link href="/ai" className="flex min-h-16 items-center gap-4 rounded-2xl border border-[#3a3a3a] bg-[#101010] p-5 active:bg-[#202020]"><Bot size={20} className="text-zinc-300"/><div><h3 className="text-sm font-medium text-white">AI设计</h3><p className="mt-1 text-xs text-zinc-300">V0.1 预留入口</p></div></Link><Link href="/search" className="flex min-h-16 items-center gap-4 rounded-2xl border border-[#3a3a3a] bg-[#101010] p-5 active:bg-[#202020]"><Search size={20} className="text-zinc-300"/><div><h3 className="text-sm font-medium text-white">联网搜索</h3><p className="mt-1 text-xs text-zinc-300">V0.1 预留入口</p></div></Link></div></section></>;
}
